version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: workshop-grafana-monitoring-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: workshop-grafana-monitoring-grafana
    environment:
      GF_PATHS_DATA : /var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
